name: base
channels:
  - conda-forge
dependencies:
  - python=3.11
  - cadquery
  - pip
  - pip:
      - streamlit
      - pydantic
      - trimesh
      - numpy
      - openai
      - pandas
      - plotly
